//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableTeacherTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvailableTeacherTime()
        {
            this.UserEnquiries = new HashSet<UserEnquiry>();
        }
    
        public long PKAvailableTeacherTimeId { get; set; }
        public long FKClassId { get; set; }
        public System.DateTime FromAvailableDate { get; set; }
        public System.DateTime ToAvailableDate { get; set; }
        public System.TimeSpan FromAvailableTime { get; set; }
        public System.TimeSpan ToAvailableTime { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEnquiry> UserEnquiries { get; set; }
        public virtual Class Class { get; set; }
    }
}
