//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.AvailableTeacherTimes = new HashSet<AvailableTeacherTime>();
            this.TeacherProfiles = new HashSet<TeacherProfile>();
            this.UserComments = new HashSet<UserComment>();
            this.UserEnquiries = new HashSet<UserEnquiry>();
            this.UserImages = new HashSet<UserImage>();
            this.UserVideos = new HashSet<UserVideo>();
        }
    
        public long PKClassId { get; set; }
        public long FKUserId { get; set; }
        public long FKSubjectId { get; set; }
        public Nullable<long> FKCityId { get; set; }
        public string ClassName { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ClassImage { get; set; }
        public string AreaName { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailableTeacherTime> AvailableTeacherTimes { get; set; }
        public virtual City City { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherProfile> TeacherProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserComment> UserComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEnquiry> UserEnquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserImage> UserImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserVideo> UserVideos { get; set; }
    }
}
