//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public long PKLoginHistoryId { get; set; }
        public long FKUserId { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime LoginDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
