//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherProfile()
        {
            this.UserEnquiries = new HashSet<UserEnquiry>();
        }
    
        public long PKTeachersId { get; set; }
        public long FKUserId { get; set; }
        public Nullable<long> FKClassId { get; set; }
        public string Experience { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public bool IsActive { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEnquiry> UserEnquiries { get; set; }
        public virtual Class Class { get; set; }
    }
}
