//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVideo
    {
        public long PKUserVideoId { get; set; }
        public long FKClassId { get; set; }
        public string VideoUrl { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
