//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEnquiry
    {
        public long PKEnquiryId { get; set; }
        public long FKUserId { get; set; }
        public long FKTeacherId { get; set; }
        public long FKAvailableTimeId { get; set; }
        public long FKClassId { get; set; }
        public System.DateTime BookedFromDate { get; set; }
        public System.DateTime BookedToDate { get; set; }
        public System.TimeSpan BookedFromTime { get; set; }
        public System.TimeSpan BookedToTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string BookingStatus { get; set; }
        public Nullable<bool> FollowUP { get; set; }
    
        public virtual TeacherProfile TeacherProfile { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual AvailableTeacherTime AvailableTeacherTime { get; set; }
        public virtual Class Class { get; set; }
    }
}
